const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.sliderbar,
		C3.Behaviors.Fade,
		C3.Behaviors.Flash,
		C3.Plugins.Particles,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.Audio.Exps.PlaybackTime,
		C3.Plugins.Audio.Exps.Duration,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Seek,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Exps.AnimationFrame
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{bg_kapak: 0},
	{Tween: 0},
	{btn_basla: 0},
	{btn_bilgi: 0},
	{btn_kaynakca: 0},
	{kaynakca: 0},
	{btn_anasayfa: 0},
	{Touch: 0},
	{Yonerge_kapak: 0},
	{bground: 0},
	{yonerge_secim: 0},
	{secim1: 0},
	{secim2: 0},
	{dinleme1: 0},
	{Audio: 0},
	{bg_sinemaSes: 0},
	{SliderBar: 0},
	{sorular1: 0},
	{btn_ileri: 0},
	{btn_geri: 0},
	{Fade: 0},
	{fakeYesil: 0},
	{fakeKirmizi1: 0},
	{fakeKirmizi2: 0},
	{fakeKirmizi3: 0},
	{Flash: 0},
	{tik: 0},
	{Sprite: 0},
	{Particles: 0},
	{sorular2: 0},
	{dogruSayisi: 0},
	{yanlisSayisi: 0},
	{yesilSayi: 0},
	{kirmiziSayi: 0},
	{btn_ses: 0},
	{buttons: 0},
	{fakeKirmizi: 0},
	{bilgi: 0},
	{secim: 0},
	{sure: 0},
	{audioControl: 0},
	{tiklama: 0},
	{dogru: 0},
	{yanlis: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	bg_kapak: class extends self.ISpriteInstance {},
	btn_basla: class extends self.ISpriteInstance {},
	btn_bilgi: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	kaynakca: class extends self.ISpriteInstance {},
	btn_anasayfa: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Yonerge_kapak: class extends self.ISpriteInstance {},
	bground: class extends self.ISpriteInstance {},
	yonerge_secim: class extends self.ISpriteInstance {},
	secim1: class extends self.ISpriteInstance {},
	secim2: class extends self.ISpriteInstance {},
	dinleme1: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	bg_sinemaSes: class extends self.ISpriteInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	sorular1: class extends self.ISpriteInstance {},
	btn_ileri: class extends self.ISpriteInstance {},
	btn_geri: class extends self.ISpriteInstance {},
	fakeYesil: class extends self.ISpriteInstance {},
	fakeKirmizi1: class extends self.ISpriteInstance {},
	fakeKirmizi2: class extends self.ISpriteInstance {},
	fakeKirmizi3: class extends self.ISpriteInstance {},
	tik: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	sorular2: class extends self.ISpriteInstance {},
	dogruSayisi: class extends self.ISpriteInstance {},
	yanlisSayisi: class extends self.ISpriteInstance {},
	yesilSayi: class extends self.ISpriteInstance {},
	kirmiziSayi: class extends self.ISpriteInstance {},
	btn_ses: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	fakeKirmizi: class extends self.ISpriteInstance {}
}